version: '3'

services:
  adcapitaldb:
    container_name: adcapitaldb
    hostname: adcapitaldb
    image: mysql
    logging:
      driver: "none"
    environment:
    - "MYSQL_ROOT_PASSWORD=welcome1"
    ports: 
    - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.5.4-management
    logging:
      driver: "none"
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASS=guest"
    ports: 
    - "5672:5672"
    - "15672:15672"

  rest:
    container_name: rest
    hostname: rest
    image: appdynamics/adcapital-tomcat
    logging:
      driver: "none"
    environment:
    - "rest=true"
    - "create_schema=true"
    - "ACCOUNT_NAME=${ACCOUNT_NAME}"
    - "ACCESS_KEY=${ACCESS_KEY}"
    - "CONTROLLER=${CONTR_HOST}"
    - "APPD_PORT=${CONTR_PORT}"
    - "APP_NAME=${APP_NAME}"
    - "NODE_NAME=${APP_NAME}_REST_NODE"
    - "TIER_NAME=Authentication-Services"
    - "EVENT_ENDPOINT=${EVENT_ENDPOINT}"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8081:8080"

  portal:
    container_name: portal
    hostname: portal
    image: appdynamics/adcapital-tomcat
    logging:
      driver: "none"
    environment:
    - "portal=true"
    - "ACCOUNT_NAME=${ACCOUNT_NAME}"
    - "ACCESS_KEY=${ACCESS_KEY}"
    - "CONTROLLER=${CONTR_HOST}"
    - "APPD_PORT=${CONTR_PORT}"
    - "APP_NAME=${APP_NAME}"
    - "NODE_NAME=${APP_NAME}_PORTAL_NODE"
    - "TIER_NAME=Portal-Services"
    - "EVENT_ENDPOINT=${EVENT_ENDPOINT}"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8082:8080"

  verification:
    container_name: verification
    hostname: verification
    image: appdynamics/adcapital-applicationprocessor
    logging:
      driver: "none"
    environment:
    - "ACCOUNT_NAME=${ACCOUNT_NAME}"
    - "ACCESS_KEY=${ACCESS_KEY}"
    - "CONTROLLER=${CONTR_HOST}"
    - "APPD_PORT=${CONTR_PORT}"
    - "APP_NAME=${APP_NAME}"
    - "NODE_NAME=${APP_NAME}_VERIFICATION_NODE"
    - "TIER_NAME=ApplicationProcessor-Service"
    - "EVENT_ENDPOINT=${EVENT_ENDPOINT}"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8083:8080"

  processor:
    container_name: processor
    hostname: processor
    image: appdynamics/adcapital-tomcat
    logging:
      driver: "none"
    environment:
    - "processor=true"
    - "ACCOUNT_NAME=${ACCOUNT_NAME}"
    - "ACCESS_KEY=${ACCESS_KEY}"
    - "CONTROLLER=${CONTR_HOST}"
    - "APPD_PORT=${CONTR_PORT}"
    - "APP_NAME=${APP_NAME}"
    - "NODE_NAME=${APP_NAME}_PROCESSOR_NODE"
    - "TIER_NAME=LoanProcessor-Services"
    - "EVENT_ENDPOINT=${EVENT_ENDPOINT}"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8084:8080"

  queuereader:
    container_name: queuereader
    hostname: queuereader
    image: appdynamics/adcapital-queuereader
    environment:
    - "ACCOUNT_NAME=${ACCOUNT_NAME}"
    - "ACCESS_KEY=${ACCESS_KEY}"
    - "CONTROLLER=${CONTR_HOST}"
    - "APPD_PORT=${CONTR_PORT}"
    - "APP_NAME=${APP_NAME}"
    - "NODE_NAME=${APP_NAME}_QUEUEREADER_NODE"
    - "TIER_NAME=Queuereader-Services"
    - "EVENT_ENDPOINT=${EVENT_ENDPOINT}"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8085:8080"

  load:
    container_name: adcapitalload
    hostname: adcapitalload
    image: appdynamics/adcapital-load
    depends_on: 
    - "portal"
    - "processor"

#  monitor:
#    container_name: monitor
#    hostname: monitor
#    image: appdynamics/adcapital-monitor
#    logging:
#      driver: "none"
#    environment:
#    - "APPD_ACCOUNT_NAME=${ACCOUNT_NAME}"
#    - "APPD_ACCESS_KEY=${ACCESS_KEY}"
#    - "APPD_HOST=${CONTR_HOST}"
#    - "APPD_PORT=${CONTR_PORT}"
#    - "APPD_SSL_ENABLED=false"
#    depends_on: 
#    - "rest"
#    - "portal"
#    - "processor"
#    - "queuereader"
#    - "verification"
