version: '3'

volumes:
  project:
  appdynamics:
    external: true

services:
  project:
    container_name: project
    image: appdynamics/adcapital-project
    volumes:
    - project:/src

  adcapitaldb:
    container_name: adcapitaldb
    hostname: adcapitaldb
    image: mysql
    logging:
      driver: "none"
    environment:
    - "MYSQL_ROOT_PASSWORD=welcome1"
    ports: 
    - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.5.4-management
    logging:
      driver: "none"
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASS=guest"
    ports: 
    - "5672:5672"
    - "15672:15672"

  rest:
    container_name: rest
    hostname: rest
    image: appdynamics/adcapital-tomcat
    volumes: 
    - project:/src
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=rest"
    - "QUIET=true"
    - "APPD_NODE_NAME=Rest"
    - "APPD_TIER_NAME=Authentication-Service"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8081:8080"

  portal:
    container_name: portal
    hostname: portal
    image: appdynamics/adcapital-tomcat
    volumes: 
    - project:/src
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=portal"
    - "QUIET=true"
    - "APPD_NODE_NAME=Portal"
    - "APPD_TIER_NAME=Portal-Service"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8082:8080"

  verification:
    container_name: verification
    hostname: verification
    image: appdynamics/adcapital-tomcat
    volumes: 
    - project:/src
    - appdynamics:/appdynamics
    env_file: ./docker-compose.env
    environment:
    - "ROLE=verification"
    - "QUIET=true"
    - "APPD_NODE_NAME=Verification"
    - "APPD_TIER_NAME=Verification-Service"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8083:8080"

  processor:
    container_name: processor
    hostname: processor
    image: appdynamics/adcapital-tomcat
    volumes: 
    - project:/src
    - appdynamics:/appdynamics
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "ROLE=processor"
    - "QUIET=true"
    - "APPD_NODE_NAME=Processor"
    - "APPD_TIER_NAME=LoanProcessor-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8084:8080"

  approval:
    container_name: approval
    hostname: approval
    image: appdynamics/adcapital-tomcat
    volumes:
    - project:/src
    - appdynamics:/appdynamics
    env_file: ./docker-compose.env
    environment:
    - "ROLE=approval"
    - "QUIET=true"
    - "APPD_NODE_NAME=Approval"
    - "APPD_TIER_NAME=Approval-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8085:8080"

  load:
    container_name: adcapitalload
    hostname: adcapitalload
    image: appdynamics/adcapital-load
    env_file: ./docker-compose.env
    depends_on: 
    - "portal"
    - "processor"

#  monitor:
#    container_name: monitor
#    hostname: monitor
#    image: appdynamics/adcapital-monitor
#    logging:
#      driver: "none"
#    env-file: ./docker-compose.env
#    depends_on: 
#    - "rest"
#    - "portal"
#    - "processor"
#    - "queuereader"
#    - "verification"
