version: '3'

volumes:
  binaries:

services:
  binaries:
    container_name: binaries
    image: appdynamics/adcapital-binaries
    volumes:
    - binaries:/src

  adcapitaldb:
    container_name: adcapitaldb
    hostname: adcapitaldb
    image: mysql
    logging:
      driver: "none"
    environment:
    - "MYSQL_ROOT_PASSWORD=welcome1"
    ports: 
    - "3306:3306"

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.5.4-management
    logging:
      driver: "none"
    environment:
    - "RABBITMQ_DEFAULT_USER=guest"
    - "RABBITMQ_DEFAULT_PASS=guest"
    ports: 
    - "5672:5672"
    - "15672:15672"

  rest:
    container_name: rest
    hostname: rest
    image: appdynamics/adcapital-tomcat
    volumes: 
    - binaries:/src
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "rest=true"
    - "create_schema=true"
    - "APPD_NODE_NAME=Rest"
    - "APPD_TIER_NAME=Authentication-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8081:8080"

  portal:
    container_name: portal
    hostname: portal
    image: appdynamics/adcapital-tomcat
    volumes: 
    - binaries:/src
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "portal=true"
    - "APPD_NODE_NAME=Portal"
    - "APPD_TIER_NAME=Portal-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8082:8080"

  verification:
    container_name: verification
    hostname: verification
    image: appdynamics/adcapital-tomcat
    volumes: 
    - binaries:/src
    env_file: ./docker-compose.env
    environment:
    - "verification=true"
    - "APPD_NODE_NAME=Verification"
    - "APPD_TIER_NAME=ApplicationProcessor-Service"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8083:8080"

  processor:
    container_name: processor
    hostname: processor
    image: appdynamics/adcapital-tomcat
    volumes: 
    - binaries:/src
    logging:
      driver: "none"
    env_file: ./docker-compose.env
    environment:
    - "processor=true"
    - "APPD_NODE_NAME=Processor"
    - "APPD_TIER_NAME=LoanProcessor-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8084:8080"

  queuereader:
    container_name: queuereader
    hostname: queuereader
    image: appdynamics/adcapital-tomcat
    volumes:
    - binaries:/src
    env_file: ./docker-compose.env
    environment:
    - "queuereader=true"
    - "APPD_NODE_NAME=Queuereader"
    - "APPD_TIER_NAME=Queuereader-Services"
    depends_on: 
    - "adcapitaldb"
    - "rabbitmq"
    ports:
    - "8085:8080"

  load:
    container_name: adcapitalload
    hostname: adcapitalload
    image: appdynamics/adcapital-load
    env_file: ./docker-compose.env
    depends_on: 
    - "portal"
    - "processor"

#  monitor:
#    container_name: monitor
#    hostname: monitor
#    image: appdynamics/adcapital-monitor
#    logging:
#      driver: "none"
#    env-file: ./docker-compose.env
#    depends_on: 
#    - "rest"
#    - "portal"
#    - "processor"
#    - "queuereader"
#    - "verification"
