version: '3'

volumes:
  appdynamics:
    external: true

services:
  monitor:
    container_name: monitor
    hostname: monitor
    build:
      context: .
      args:
        MACHINE_AGENT_ZIP:
        MACHINE_AGENT_SHA256:
    image: appdynamics/appdynamics-monitor
    environment:
      APPD_DOCKER_VISIBILITY:
      APPD_ANALYTICS_MONITOR:
    env_file: ../docker-compose.env
      
networks:
  default:
    external:
      name: adcapitaldocker_default
