version: '3'

volumes:
  appdynamics:
    external: true

services:
  project:
    build:
      context: .
      args:
        APPD_AGENT_ZIP:
        APPD_AGENT_SHA256:
    container_name: appdynamics
    image: appdynamics/adcapital-agents
    environment:
        APPD_DIR: "/appdynamics"
    volumes:
    - appdynamics:/appdynamics
